name: CD

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "sphinx-build -b html . _build"
        docs-folder: "source/"
        
    - name: Commit documentation changes
      run: |
        git clone https://github.com/gacarrillor/test-public-sphinx-docs.git --branch gh-pages --single-branch gh-pages
        cp -r source/_build/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
        
    #- name: Push changes
    #  uses: ad-m/github-push-action@master
    #  with:
    #    branch: gh-pages
    #    directory: gh-pages
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    repository: 'gacarrillor/test-public-sphinx-docs'

    - name: Pushes to deploy repository
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'gh-pages'
        destination-github-username: 'gacarrillor'
        destination-repository-name: 'test-public-sphinx-docs'
        user-email: gcarrillo@linuxmail..org
        target-branch: gh-pages
        commit-message: 'Automatic deploy from commit in docs repo'
